sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t hozefam/docker-react-app -f Dockerfile.dev Dockerfile.dev .

script:
  - docker run -e CI=true hozefam/docker-react-app npm run test
